[window]
opacity = 0.95
decorations = "none"
startup_mode = "Windowed"
dynamic_padding = false

[window.padding]
x = 4
y = 4

[font]
size = 10.5

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[cursor.style]
shape = "Block"
blinking = "Never"

[shell]
program = "/bin/zsh"

[colors.primary]
background = "#1e2127"
foreground = "#dcdfe4"

[colors.normal]
black   = "#1e2127"
red     = "#e06c75"
green   = "#98c379"
yellow  = "#d19a66"
blue    = "#61afef"
magenta = "#c678dd"
cyan    = "#56b6c2"
white   = "#abb2bf"

[colors.bright]
black   = "#5c6370"
red     = "#e06c75"
green   = "#98c379"
yellow  = "#d19a66"
blue    = "#61afef"
magenta = "#c678dd"
cyan    = "#56b6c2"
white   = "#ffffff"
